@startuml seq_updateBooking

skinparam {
    defaultFontName Source Code Pro
    defaultFontSize 18
    shadowing false
    componentStyle uml2
    MinClassWidth 150
    ParticipantPadding 80
    ArrowThickness 1.5
}

actor "**User**" as User
participant "**Bookings Router**" as BR           #98FB98
participant "**Auth Middleware**" as AM           #FF6347
participant "**Bookings Controller**" as BC       #FFD700
participant "**Booking Model**" as BM             #87CEEB
participant "**Car Model**" as CM                 #87CEEB
database "**MongoDB**" as DB                      #FFDEAD

== Update booking ==

User -> BR: PUT /api/bookings/:id
activate User                                     #D3D3D3
activate BR                                       #98FB98
BR -> AM: protect, authorize('user','admin')
activate AM                                       #FF6347
AM -> BC: updateBooking
activate BC                                       #FFD700
BC -> BM: Booking.findById(id)
activate BM                                       #87CEEB
BM --> DB: Query booking by id
activate DB                                       #FFDEAD
DB --> BM: booking / null
deactivate DB
BM --> BC: booking / null
deactivate BM
BC -> CM: (optional) Car availability updates if car changed
activate CM                                       #87CEEB
CM --> DB: Query/Update car availability
activate DB                                       #FFDEAD
DB --> CM: ok / not available
deactivate DB
CM --> BC: ok / not available
deactivate CM
BC -> BM: Booking.findByIdAndUpdate(id, body)
activate BM                                       #87CEEB
BM --> DB: UPDATE booking
activate DB                                       #FFDEAD
DB --> BM: updated booking
deactivate DB
BM --> BC: updated booking
deactivate BM
BC -> User: 200 OK / 404 Not Found / 401 Unauthorized
deactivate BC
deactivate AM
deactivate BR
deactivate User

@enduml
